sudo: required
services: 
  - docker

language: java
jdk: 
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: true

script:
  - cd APIGateway && ./mvnw clean install -DskipTests
  - cd ../ConfigServer && ./mvnw clean install -DskipTests
  - cd ../EmployeeDashBoard && ./mvnw clean install -DskipTests
  - cd ../EmployeeSearch && ./mvnw clean install -DskipTests
  - cd ../EurekaServer && ./mvnw clean install -DskipTests

after_script
  - docker-compose up --build