language: java

jdk: 
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

sudo: required

services:
- docker

install: true

script:
  - ./ConfigServer/mvnw clean install -DskipTests
  - ./EurekaServer/mvnw clean install -DskipTests
  - ./EmployeeDashBoard/mvnw clean install -DskipTests
  - ./EmployeeSearch/mvnw clean install -DskipTests
  - ./APIGateway/mvnw clean install -DskipTests

after_success:
  # Build Images
  - docker build --tag=alpine-jdk:base --rm=true ./Base-Image 
  - docker build -t parnabbasak/multi-configserver -f Dockerfile-configserver ./ConfigServer
  - docker build -t parnabbasak/multi-eurekaserver -f Dockerfile-EurekaServer ./EurekaServer
  - docker build -t parnabbasak/multi-employeedashboard -f Dockerfile-EmployeeDashBoard ./EmployeeDashBoard
  - docker build -t parnabbasak/multi-employeesearch -f Dockerfile-EmployeeSearch ./EmployeeSearch
  - docker build -t parnabbasak/multi-apigateway -f Dockerfile-APIGateway ./APIGateway

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Take the built images and push to docker hub
  - docker push parnabbasak/multi-configserver
  - docker push parnabbasak/multi-eurekaserver
  - docker push parnabbasak/multi-employeedashboard
  - docker push parnabbasak/multi-employeesearch
  - docker push parnabbasak/multi-apigateway