language: java

jdk: 
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

sudo: required

services:
- docker

install: true

script:
  - cd APIGateway && ./mvnw clean install -DskipTests
  - cd ../ConfigServer && ./mvnw clean install -DskipTests
  - cd ../EmployeeDashBoard && ./mvnw clean install -DskipTests
  - cd ../EmployeeSearch && ./mvnw clean install -DskipTests
  - cd ../EurekaServer && ./mvnw clean install -DskipTests

after_script:
  - docker build -t parnabbasak/multi-APIGateway -f ./APIGateway/Dockerfile-APIGateway ./APIGateway
  - docker build -t parnabbasak/multi-ConfigServer -f ./ConfigServer/Dockerfile-configserver ./ConfigServer