FROM alpine-jdk:base
MAINTAINER parnab
RUN apk --no-cache add netcat-openbsd
COPY EmployeeDashboard/target/EmployeeDashBoard-0.0.1-SNAPSHOT.jar /opt/lib/
COPY EmployeeDashboard/EmployeeDashBoard-entrypoint.sh /opt/bin/EmployeeDashBoard-entrypoint.sh
RUN chmod 755 /opt/bin/EmployeeDashBoard-entrypoint.sh
EXPOSE 8080
