FROM alpine-jdk:base
MAINTAINER parnab
RUN apk --no-cache add netcat-openbsd
COPY EmployeeSearch/target/EmployeeSearch-0.0.1-SNAPSHOT.jar /opt/lib/
COPY EmployeeSearch/EmployeeSearch-entrypoint.sh /opt/bin/EmployeeSearch-entrypoint.sh
RUN chmod 755 /opt/bin/EmployeeSearch-entrypoint.sh
EXPOSE 8080
