FROM alpine-jdk:base
MAINTAINER Parnab
COPY ConfigServer/target/ConfigServer-0.0.1-SNAPSHOT.jar /opt/lib/
RUN mkdir /var/lib/config-repo
COPY ConfigServer/config-repo /var/lib/config-repo
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/ConfigServer-0.0.1-SNAPSHOT.jar"]
VOLUME /var/lib/config-repo
EXPOSE 9090